In [2]:
import numpy as np
import pandas as pd

In [24]:
balloon1 = pd.read_csv("adult+stretch.csv", skiprows=[1, 2])
balloon2 = pd.read_csv("adult-stretch.csv", skiprows=[1, 2])
balloon3 = pd.read_csv("yellow-small+adult-stretch.csv", skiprows=[1, 2])
balloon4 = pd.read_csv("yellow-small.csv", skiprows=[1, 2])

In [29]:
meta = pd.read_csv("adult+stretch.csv", nrows=2)
meta.head()

      Color  Size  Act  Age  Inflated
0         2   2.0  2.0  2.0       2.0
1  Inflated   NaN  NaN  NaN       NaN

In [26]:
balloons = pd.concat([balloon1, balloon2, balloon3, balloon4], ignore_index=True)

In [27]:
balloons.head()

    Color   Size      Act    Age Inflated
0  YELLOW  SMALL  STRETCH  ADULT        T
1  YELLOW  SMALL  STRETCH  ADULT        T
2  YELLOW  SMALL  STRETCH  CHILD        F
3  YELLOW  SMALL      DIP  ADULT        F
4  YELLOW  SMALL      DIP  CHILD        F